# All project build tasks go here. These tasks will only be run for the
# specified commit if the commit hasn't been deployed before or if "force"
# is true.

# Modify as-needed!

- name: npm init
  become: yes
  shell: npm init -y
  args:
    chdir: "{{clone_path}}"

# We need to use `npm ci` to avoid changing package-lock.json and causing git conflicts
- name: Install packages based on package-lock.json
  become: yes
  shell: npm ci
  args:
    chdir: "{{clone_path}}"

# - name: install npm modules
#   npm: path="{{clone_path}}"

- name: build production version
  become: yes
  shell: npm run build
  args:
    chdir: "{{clone_path}}"
  environment:
    APP_ENV: "{{env}}"

- name: generate build info file
  template: src=build_info.txt dest={{clone_path}}/{{build_info_path}}
  when: build_info_path is defined
